### ISSUE TITLE
Viewing event list

### ISSUE THREAD

**Issue by AJGreaves** [AJGreaves/project-planning#5]
**User Story:** 

As a local resident, I want to see a list of upcoming community events, so that I can find interesting events to attend.

**Acceptance Criteria:**

- [ ] The homepage displays a list of upcoming community events.
- [ ] Each event listing includes the event name, date, time, and a brief description.
- [ ] The list is responsive and looks good on all main device sizes.

**Tasks:**

- [ ] Add an HTML section on the homepage dedicated to upcoming community events.
- [ ] Style the event list using Bootstrap.
- [ ] Add some sample events including event name, date, time, and brief description.
